### ISSUE TITLE
EXTRATION FAILED 

### ISSUE THREAD

**Issue by marcelo321** [nccgroup/Winpayloads#23]
EXTRATION FAILED 

unable to find a volume for file extration, please verify that you have proper permissions.
i click ok. and after the installation completes i can't start the prgramm because there is no directory. plss help!!

here is the error

[*] Downloading Python27, Pywin32 and Pycrypto For Wine 
--2017-06-16 18:42:29--  https://www.python.org/ftp/python/2.7.10/python-2.7.10.msi
Resolviendo www.python.org (www.python.org)... 151.101.24.223, 2a04:4e42:6::223
Conectando con www.python.org (www.python.org)[151.101.24.223]:443... conectado.
Petición HTTP enviada, esperando respuesta... 200 OK
Longitud: 18423808 (18M) [application/octet-stream]
Grabando a: “python-2.7.10.msi”

python-2.7.10.msi        100%[==================================>]  17,57M   466KB/s    in 80s     

2017-06-16 18:43:50 (225 KB/s) - “python-2.7.10.msi” guardado [18423808/18423808]

err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "C:\Python27\lib\runpy.py", line 109, in _get_module_details
    return _get_module_details(pkg_main_name)
  File "C:\Python27\lib\runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "C:\Python27\lib\pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "C:\Python27\lib\pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "C:\Python27\lib\pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "C:\Python27\lib\ensurepip\__init__.py", line 9, in <module>
    import tempfile
  File "C:\Python27\lib\tempfile.py", line 35, in <module>
    from random import Random as _Random
  File "C:\Python27\lib\random.py", line 885, in <module>
    _inst = Random()
  File "C:\Python27\lib\random.py", line 97, in __init__
    self.seed(x)
  File "C:\Python27\lib\random.py", line 113, in seed
    a = long(_hexlify(_urandom(2500)), 16)
WindowsError: [Error -2146893801] Windows Error 0x80090017
err:msi:ITERATE_Actions Execution halted, action L"UpdatePip" returned 1627
err:ole:CoGetClassObject class {00021401-0000-0000-c000-000000000046} not registered
err:ole:CoGetClassObject no class object {00021401-0000-0000-c000-000000000046} could be created for context 0x1
err:msi:ITERATE_CreateShortcuts CLSID_ShellLink not available
err:ole:CoGetClassObject class {00021401-0000-0000-c000-000000000046} not registered
err:ole:CoGetClassObject no class object {00021401-0000-0000-c000-000000000046} could be created for context 0x1
err:msi:ITERATE_CreateShortcuts CLSID_ShellLink not available
err:ole:CoGetClassObject class {00021401-0000-0000-c000-000000000046} not registered
err:ole:CoGetClassObject no class object {00021401-0000-0000-c000-000000000046} could be created for context 0x1
err:msi:ITERATE_CreateShortcuts CLSID_ShellLink not available
err:ole:CoGetClassObject class {00021401-0000-0000-c000-000000000046} not registered
err:ole:CoGetClassObject no class object {00021401-0000-0000-c000-000000000046} could be created for context 0x1
err:msi:ITERATE_CreateShortcuts CLSID_ShellLink not available
err:ole:CoGetClassObject class {00021401-0000-0000-c000-000000000046} not registered
err:ole:CoGetClassObject no class object {00021401-0000-0000-c000-000000000046} could be created for context 0x1
err:msi:ITERATE_CreateShortcuts CLSID_ShellLink not available
--2017-06-16 18:43:55--  http://www.voidspace.org.uk/downloads/pycrypto26/pycrypto-2.6.win32-py2.7.exe
Resolviendo www.voidspace.org.uk (www.voidspace.org.uk)... 207.38.86.245
Conectando con www.voidspace.org.uk (www.voidspace.org.uk)[207.38.86.245]:80... conectado.
Petición HTTP enviada, esperando respuesta... 200 OK
Longitud: 972594 (950K) [application/x-msdownload]
Grabando a: “pycrypto-2.6.win32-py2.7.exe”

pycrypto-2.6.win32-py2.7 100%[==================================>] 949,80K   469KB/s    in 2,0s    

2017-06-16 18:43:58 (469 KB/s) - “pycrypto-2.6.win32-py2.7.exe” guardado [972594/972594]

**Comment by marcelo321** [comment]
cd ~/.wine/dosdevices
ln -s /tmp HardDisk0
ln -s HardDisk0 t:
