### ISSUE TITLE
problem when execute winpayloads

### ISSUE THREAD

**Issue by jcdex69** [nccgroup/Winpayloads#25]
Hi, 

I have this error when execute winpayloads : 

Traceback (most recent call last):
  File "./WinPayloads.py", line 5, in <module>
    from lib.menu import *
  File "/root/Git/winpayloads/lib/menu.py", line 4, in <module>
    from generatepayload import *
  File "/root/Git/winpayloads/lib/generatepayload.py", line 3, in <module>
    from psexecspray import *
  File "/root/Git/winpayloads/lib/psexecspray.py", line 29, in <module>
    t = blessings.Terminal()
NameError: name 'blessings' is not defined

I try to reinstall, git pull, ...

kali 4.9.0-kali4-amd64

Thx

**Comment by imnewbe** [comment]
i had met this situation too.

**Comment by pieterhouwen** [comment]
Me 2, also running kali amd64 up-to-date

**Comment by Marantral** [comment]
I have also run into this issue.

**Comment by Charliedean** [comment]
Thanks All,
This should have been fixed now.
Please run setup.sh again to redownload the psexecpray module.

Charlie
