### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by imnewbe** [nccgroup/Winpayloads#27]
Traceback (most recent call last):
  File "WinPayloads.py", line 41, in <module>
    getAndRunMainMenu()
  File "/Users/xxxx/winpayloads/lib/menu.py", line 61, in getAndRunMainMenu
    mainMenu.runmenu()
  File "/Users/xxxxx/winpayloads/lib/menu.py", line 115, in runmenu
    result = extrawork(payloadchoice,payload)
  File "/Users/xxxxx/winpayloads/lib/preparepayload.py", line 31, in reversePayloadGeneration
    portnum,ipaddr = reverseIpAndPort('4444')
  File "/Users/xxxx/winpayloads/lib/preparepayload.py", line 20, in reverseIpAndPort
    '\n[*] Press Enter To Get Local Ip Automatically(%s)\n[*] IP> '%(t.bold_green + IP + t.normal))

**Comment by Charliedean** [comment]
Hi,

Can you post the full traceback please?

Thanks

**Comment by imnewbe** [comment]
[*] Press Enter For Default Port(4444)
[*] Port>
Traceback (most recent call last):
  File "WinPayloads.py", line 41, in <module>
    getAndRunMainMenu()
  File "/Users/yx/winpayloads/lib/menu.py", line 61, in getAndRunMainMenu
    mainMenu.runmenu()
  File "/Users/yx/winpayloads/lib/menu.py", line 115, in runmenu
    result = extrawork(payloadchoice,payload)
  File "/Users/yx/winpayloads/lib/preparepayload.py", line 31, in reversePayloadGeneration
    portnum,ipaddr = reverseIpAndPort('4444')
  File "/Users/yx/winpayloads/lib/preparepayload.py", line 20, in reverseIpAndPort
    '\n[*] Press Enter To Get Local Ip Automatically(%s)\n[*] IP> '%(t.bold_green + IP + t.normal))
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by Charliedean** [comment]
Thanks!
This has been fixed in the latest commit.
https://github.com/nccgroup/Winpayloads/commit/4419f079f477eaa1096f36430cfffe74ec58b5a7
It was due to the fact that you do not have a active connection.

Charlie
