### ISSUE TITLE
 Installation problem 

### ISSUE THREAD

**Issue by ainihaozhu** [nccgroup/Winpayloads#34]
hi,
I am trying to run Winpayloads on my parrot(Linux parrot 4.11.0-parrot6-amd64) machine but it seems to have failed and i get the following error:
Main Menu > 2
[*] Press Enter For Default Port(4444)
[*] Port> 123

[*] Press Enter To Get Local Ip Automatically(192.168.68.104)
[*] IP> 
[*] IP SET AS 192.168.68.104
[*] PORT SET AS 123

[*] Try UAC Bypass(Only Works For Local Admin Account)? y/[n]:y
[*] Creating Payload using Pyinstaller...
mv: cannot stat 'dist/payload.exe': 没有那个文件或目录

[*] Payload.exe Has Been Generated And Is Located Here: /root/winpayloads/Windows_Meterpreter_Reverse_Shell.exe
rm: cannot remove 'dist': 没有那个文件或目录
rm: cannot remove 'build': 没有那个文件或目录
rm: cannot remove '*.spec': 没有那个文件或目录

[*] Upload To Local Websever or (p)sexec? [y]/p/n: 

/root/winpayloads is empty.not creat payloads.
When i trying  to  steup.sh -r ,but it seems to have failed  and i get the following erro:
wine: cannot find '/root/.wine/drive_c/Python27/python.exe'
..................
2017-07-26 21:56:24 (1.67 MB/s) - 已保存 “python-2.7.10.msi.1” [18423808/18423808])

err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "C:\Python27\lib\runpy.py", line 109, in _get_module_details
    return _get_module_details(pkg_main_name)
  File "C:\Python27\lib\runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "C:\Python27\lib\pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "C:\Python27\lib\pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "C:\Python27\lib\pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "C:\Python27\lib\ensurepip\__init__.py", line 9, in <module>
    import tempfile
  File "C:\Python27\lib\tempfile.py", line 35, in <module>
    from random import Random as _Random
  File "C:\Python27\lib\random.py", line 885, in <module>
    _inst = Random()
  File "C:\Python27\lib\random.py", line 97, in __init__
    self.seed(x)
  File "C:\Python27\lib\random.py", line 113, in seed
    a = long(_hexlify(_urandom(2500)), 16)
WindowsError: [Error -2146893801] Windows Error 0x80090017
err:msi:ITERATE_Actions Execution halted, action L"UpdatePip" returned 1627

........................

My english is bad ,excuse me!
thanks
parrot

**Comment by PrettyBoyPBM** [comment]
same here :c on RaspBerryPi 3 B
