### ISSUE TITLE
Please help with this issue Starting Winpayloads

### ISSUE THREAD

**Issue by PrettyBoyPBM** [nccgroup/Winpayloads#42]
root@kali-pi:~/Winpayloads# ./WinPayloads.py
Traceback (most recent call last):
  File "./WinPayloads.py", line 2, in <module>
    from lib.main import *
  File "/root/Winpayloads/lib/main.py", line 28, in <module>
    t = blessed.Terminal()
AttributeError: 'module' object has no attribute 'Terminal'

**Comment by Charliedean** [comment]
Hi,
Please post output of `./setup.sh -r`
