### ISSUE TITLE
from pyasn1.type.univ import noValue - impacket

### ISSUE THREAD

**Issue by smoklessfire** [nccgroup/Winpayloads#48]
i follow the step, then re install it with the ./setup.sh -r ... and stil get this error when strt running the python file.
what seem be the probleme ? 

the error response after running the file : 
'XXXXXXX'~/pentest/Winpayloads# ./WinPayloads.py 
Traceback (most recent call last):
  File "./WinPayloads.py", line 2, in <module>
    from lib.main import *
  File "/root/pentest/Winpayloads/lib/main.py", line 19, in <module>
    import psexec
  File "/root/pentest/Winpayloads/lib/psexec.py", line 27, in <module>
    from impacket import version, smb
  File "/usr/local/lib/python2.7/dist-packages/impacket/smb.py", line 49, in <module>
    from pyasn1.type.univ import noValue
ImportError: cannot import name noValue

**Comment by Closecallexception** [comment]
I have the exact same issue, can we have a discussion to resolve this?

**Comment by Charliedean** [comment]
Hi,
I will look into this when I have some time.
Is this a fresh install for you? If so what distro?

**Comment by Charliedean** [comment]
Hi guys, just done a 2 minute Google and have found the bug. It's with impacket(a module)
Please see the following
https://github.com/CoreSecurity/impacket/issues/355

Thanks

**Comment by Himan6** [comment]
**solution** rm -rf /usr/local/lib/python2.7/dist-packages/impacket*

**Comment by smoklessfire** [comment]
hye guys, 
sorry, wasn't able to spend time this 2 last week, was in exams sessions ...
but really thanks for the help, i moved to other payload gen, and still learning in more deep how all this work. !

reguards,
smokless-fire.
