### ISSUE TITLE
import Error

### ISSUE THREAD

**Issue by cleanshotpow** [nccgroup/Winpayloads#50]
hello, thanks for ur effort and help.

i cant find the solution,  help me plz~!

root@kali:~/Winpayloads# ./WinPayloads.py
Traceback (most recent call last):
  File "./WinPayloads.py", line 2, in <module>
    from lib.main import *
  File "/root/Winpayloads/lib/main.py", line 19, in <module>
    import psexec
  File "/root/Winpayloads/lib/psexec.py", line 27, in <module>
    from impacket import version, smb
  File "/usr/local/lib/python2.7/dist-packages/impacket/smb.py", line 49, in <module>
    from pyasn1.type.univ import noValue
ImportError: cannot import name noValue

System environment : 

intel i5-4690 3.50
16gb ram
windows 7 Ultimate
Debian 8.x 64bit VMware
 kali-linux-2017.3-amd64.iso
python version :  2.7.14 
pip version ; pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)

**Comment by Charliedean** [comment]
https://github.com/nccgroup/Winpayloads/issues/48
