### ISSUE TITLE
Errors when running python WinPayloads.py 

### ISSUE THREAD

**Issue by minty-highway** [nccgroup/Winpayloads#52]
Hi I have run setup.sh on a Kali Rolling box and then attempted to run WinPayloads.py and get the following errors.....
any advice appreciated.

e is 65537 (0x010001)
writing RSA key
Signature ok
subject=C = US, ST = Denial, L = Springfield, O = Dis, CN = www.example.com
Getting Private key
[*] Done 
[*] Cleaning Up 
[*] Done 
root@minty:~/Desktop/Winpayloads# 
root@minty:~/Desktop/Winpayloads# python WinPayloads.py 
Traceback (most recent call last):
  File "WinPayloads.py", line 2, in <module>
    from lib.main import *
  File "/root/Desktop/Winpayloads/lib/main.py", line 19, in <module>
    import psexec
  File "/root/Desktop/Winpayloads/lib/psexec.py", line 27, in <module>
    from impacket import version, smb
  File "/usr/local/lib/python2.7/dist-packages/impacket/smb.py", line 49, in <module>
    from pyasn1.type.univ import noValue
ImportError: cannot import name noValue

**Comment by Charliedean** [comment]
Duplicate..
https://github.com/nccgroup/Winpayloads/issues/48
Please look at other open issues before posting
