### ISSUE TITLE
launch error on parrot os 

### ISSUE THREAD

**Issue by steevespapillon** [nccgroup/Winpayloads#62]
when i try to launch Winpayloads :
Traceback (most recent call last):
  File "./WinPayloads.py", line 2, in <module>
    from lib.main import *
  File "/opt/Winpayloads/lib/main.py", line 8, in <module>
    import blessed
ImportError: No module named blessed

**Comment by steevespapillon** [comment]
pip install  blessed 
Requirement already satisfied: blessed in /usr/local/lib/python3.6/dist-packages (1.15.0)
Requirement already satisfied: six>=1.9.0 in /home/mc/.local/lib/python3.6/site-packages (from blessed) (1.11.0)
Requirement already satisfied: wcwidth>=0.1.4 in /usr/local/lib/python3.6/dist-packages (from blessed) (0.1.7)

**Comment by steevespapillon** [comment]
resolved thank you
