### ISSUE TITLE
latest version 

### ISSUE THREAD

**Issue by mironetwo12** [nccgroup/Winpayloads#65]
Checking if up-to-date || ctr + c to cancel
Traceback (most recent call last):
  File "./WinPayloads.py", line 44, in <module>
    getAndRunMainMenu()
  File "/home/skynet/Desktop/Winpayloads/lib/menu.py", line 62, in getAndRunMainMenu
    mainMenu = MenuOptions(mainMenuOptions(), menuName="Main Menu")
  File "/home/skynet/Desktop/Winpayloads/lib/menu.py", line 80, in mainMenuOptions
    ('interface', {'payloadchoice': None, 'payload': 'Set Default Network Interface', 'extrawork': doInterfaceSelect, 'params': None, 'availablemodules': {returnINTER(): ''}}),
  File "/home/skynet/Desktop/Winpayloads/lib/menu.py", line 18, in returnINTER
    return str(GetIP.ChooseInterface()['interface'])
  File "/home/skynet/Desktop/Winpayloads/lib/main.py", line 91, in ChooseInterface
    return defaultsetinterface
UnboundLocalError: local variable 'defaultsetinterface' referenced before assignment

what I should to do? how to fix this error?

**Comment by Charliedean** [comment]
Hi,

Thanks for this.

The latest commit should have fixed it.
https://github.com/nccgroup/Winpayloads/commit/98b9625685141cdb04439a1995a44e37fb4e11c9

Cheers

**Comment by Charliedean** [comment]
Issue still present. It happens when the user does not have an active network connection/default interface.

Looking into fixing it now.

**Comment by Charliedean** [comment]
Should be fixed as of latest merge.
https://github.com/nccgroup/Winpayloads/pull/67
