### ISSUE TITLE
not install correctly 

### ISSUE THREAD

**Issue by gnu-like** [nccgroup/Winpayloads#70]
```
Traceback (most recent call last):
  File "/opt/pyinstaller/pyinstaller.py", line 14, in <module>
    from PyInstaller.__main__ import run
  File "Z:\opt\pyinstaller\PyInstaller\__main__.py", line 21, in <module>
    import PyInstaller.building.build_main
  File "Z:\opt\pyinstaller\PyInstaller\building\build_main.py", line 32, in <module>
    from ..depend import bindepend
  File "Z:\opt\pyinstaller\PyInstaller\depend\bindepend.py", line 38, in <module>
    from ..utils.win32.winmanifest import RT_MANIFEST
  File "Z:\opt\pyinstaller\PyInstaller\utils\win32\winmanifest.py", line 97, in <module>
    from PyInstaller.utils.win32 import winresource
  File "Z:\opt\pyinstaller\PyInstaller\utils\win32\winresource.py", line 20, in <module>
    import pywintypes
ImportError: No module named pywintypes
```

I did `./setup.sh -r` not solved

**Comment by Charliedean** [comment]
Could you please give the output from the setup.sh script so i can debug?

In the meantime you can use Winpayloads in docker.
