### ISSUE TITLE
Cannot import name logger 

### ISSUE THREAD

**Issue by millionhz** [nccgroup/Winpayloads#75]
When i run the ./Winpayloads.py file i get this error:
Traceback (most recent call last):
  File "./WinPayloads.py", line 2, in <module>
    from lib.main import *
  File "/root/Winpayloads/lib/main.py", line 20, in <module>
    import psexec
  File "/root/Winpayloads/lib/psexec.py", line 26, in <module>
    from impacket import logger
ImportError: cannot import name logger

the installation showed no errors.

**Comment by Charliedean** [comment]
Should be fixed as of https://github.com/nccgroup/Winpayloads/commit/809c97090fc151ff7c0d1ab602ce06ca28db094b

But keep in mind that the setup.sh install is deprecated and docker is advised.
