### ISSUE TITLE
Problem when executing Winpayload.py

### ISSUE THREAD

**Issue by Diatemba99** [nccgroup/Winpayloads#84]
# Using python and python2
Traceback (most recent call last):
  File "WinPayloads.py", line 2, in <module>
    from lib.main import *
  File "/home/kali/Downloads/tools/Winpayloads/lib/main.py", line 9, in <module>
    import blessed
ImportError: No module named blessed

# Using python 3
File "WinPayloads.py", line 11
    print t.bold_red + "[!] Rerun the setup.sh" + t.normal
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(t.bold_red + "[!] Rerun the setup.sh" + t.normal)?

**Comment by Diatemba99** [comment]
I need help.

**Comment by Rems08** [comment]
Same ++

**Comment by C2Pwn** [comment]
Follow install instructions via docker.

**Comment by conan3hh** [comment]
root@kali:/opt/Winpayloads# python2 WinPayloads.py 
Traceback (most recent call last):
  File "WinPayloads.py", line 2, in <module>
    from lib.main import *
  File "/opt/Winpayloads/lib/main.py", line 20, in <module>
    import psexec
  File "/opt/Winpayloads/lib/psexec.py", line 31, in <module>
    from impacket import version, smb
  File "/usr/local/lib/python2.7/dist-packages/impacket-0.9.25.dev1+20220428.174722.95a48050-py2.7.egg/impacket/smb.py", line 60, in <module>
    from impacket.krb5.gssapi import KRB5_AP_REQ
  File "/usr/local/lib/python2.7/dist-packages/impacket-0.9.25.dev1+20220428.174722.95a48050-py2.7.egg/impacket/krb5/gssapi.py", line 23, in <module>
    from Cryptodome.Hash import HMAC, MD5
ImportError: No module named Cryptodome.Hash.

How i can fix it ?
