### ISSUE TITLE
Error In Creating Payload... Exiting..

### ISSUE THREAD

**Issue by sherubinsky** [nccgroup/Winpayloads#9]
Hi i have some trouble to test this tool i got this error 

Python 2.7.11+
Kali 2016 32 bit fully updated

[*] Error In Creating Payload... Exiting..

Executing wine (wineserver32) 1.8.1 on Debian Kali Linux Rolling (i386).
If something goes wrong, please rerun with "WINEDEBUG=err+all wine"
for more detailed debugging output.
291 INFO: wrote /etc/winpayloads\payload.spec
431 INFO: Testing for ability to set icons, version resources...
450 INFO: ... resource update available
476 INFO: UPX is not available.
Traceback (most recent call last):
  File "/opt/pyinstaller-2.0/pyinstaller.py", line 91, in <module>
    main()
  File "/opt/pyinstaller-2.0/pyinstaller.py", line 86, in main
    run_build(opts, spec_file)
  File "/opt/pyinstaller-2.0/pyinstaller.py", line 50, in run_build
    PyInstaller.build.main(spec_file, **opts.**dict**)
  File "Z:\opt\pyinstaller-2.0\PyInstaller\build.py", line 1625, in main
    build(specfile, buildpath)
  File "Z:\opt\pyinstaller-2.0\PyInstaller\build.py", line 1582, in build
    execfile(spec)
  File "/etc/winpayloads\payload.spec", line 5, in <module>
    hookspath=None)
  File "Z:\opt\pyinstaller-2.0\PyInstaller\build.py", line 371, in **init**
    raise ValueError("script '%s' not found" % script)
ValueError: script '/etc/winpayloads/payload.py' not found

[*] Cleaning Up

If someone are able to help it will be appreciable ,thanks.

**Comment by Charliedean** [comment]
This should have been fixed in the latest commits. Thanks
